# Generated by Django 4.1.7 on 2023-03-01 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Brand",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("logo", models.ImageField(upload_to="images/")),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField()),
                ("website", models.URLField()),
                ("email", models.EmailField(max_length=254)),
                ("phone", models.CharField(max_length=20)),
                ("address", models.CharField(max_length=200)),
                ("city", models.CharField(max_length=200)),
                ("state", models.CharField(max_length=200)),
                ("zip_code", models.CharField(max_length=200)),
                ("country", models.CharField(max_length=200)),
                ("date_added", models.DateTimeField(auto_now_add=True)),
                ("date_updated", models.DateTimeField(auto_now=True)),
                ("delivery_time", models.CharField(max_length=200)),
                ("delivery_fee", models.CharField(max_length=200)),
                ("product_categories", models.CharField(max_length=200)),
            ],
        ),
    ]
